#+STARTUP: showall
#+LaTeX_CLASS_OPTIONS: [a4paper,10pt]
#+OPTIONS: toc:nil
#+LaTeX_HEADER: \usepackage[light]{kpfonts}
#+LaTeX_HEADER: \usepackage[english,italian]{babel}
#+LaTeX_HEADER: \usepackage{layaureo}

* Fermi Spacecraft and Instruments ([[http://www.nasa.gov/mission_pages/GLAST/spacecraft/index.html][fonte]])
**  Fermi Instruments

    The Fermi Gamma-ray Space Telescope (formerly called GLAST) is an
    international and multi-agency space observatory that will study the cosmos
    in the photon energy range of 8,000 electronvolts (8 keV) to greater than
    300 billion electronvolts (300 GeV). An electronvolt is a unit of energy
    close to that of visible light, so Fermi will catch photons with energies
    thousands to hundreds of billions of times greater than those we see with
    our eyes (1 keV = 1,000 eV, 1 MeV = 1,000,000 eV, 1 GeV = 1,000,000,000 eV).

    Fermi carries two instruments: the *Large Area Telescope (LAT)* and
    the *GLAST Burst Monitor (GBM)*. The LAT is Fermi’s primary instrument, and
    the GBM is the complementary instrument.

** Requirements for the LAT and GBM

   Based on our knowledge of the gamma-ray sky from previous missions,
   scientists defined the following requirements for the Fermi instruments:

   + *The Large Area Telescope (LAT)*

    * Because the sky at gamma-ray energies has so many variable sources, the
      LAT must have a large field of view, over 2 steradians (one-fifth of the
      entire sky).
    * To identify and study sources accurately, the LAT must be able to measure
      the locations of bright sources to within 1 arcminute (about 1/30 of the
      diameter of the full Moon).
    * The study of gamma rays covers a broad energy range, so the LAT must catch
      photons with energies from 30 MeV to greater than 300 GeV. In particular,
      the LAT will have high sensitivity above 10 GeV, because almost nothing is
      known about cosmic objects at these energies.
    * Since gamma-ray bursts can release a torrent of gamma rays within a
      fraction of a second, the LAT must be able to measure gamma rays over
      short time intervals.
    * Because scientists need long observations to understand many types of
      sources, the LAT should be able to operate for many years without
      degradation.
    * Because of the high flux of cosmic rays, which can mask the much smaller
      flux of gamma rays, the LAT must be able to reject 99.999% of signals
      generated by cosmic rays.

   + *The GLAST Burst Monitor (GBM)*

    * Gamma-ray bursts (GRBs) come from random directions of the sky, so the GBM
      must watch as much of the entire sky as possible at all times.
    * To gain the most information about GRBs, the GBM should be able to measure
      photon energies over a wide range, down to 8 keV and up to energies that
      overlap the LAT energy range.
    * Since GRBs last from mere microseconds to thousands of seconds, the GBM
      must be able to detect GRBs over a wide range of timescales.

** The instruments

*** Large Area Telescope (LAT)

    The LAT has four subsystems that work together to detect gamma rays and to
    reject signals from the intense bombardment of cosmic rays. For every gamma
    ray that enters the LAT, it will have to filter out 100,000 to one million
    cosmic rays, charged particles that resemble the particles produced by gamma
    rays. The four main subsystems are:

    + *Tracker*
    + *Calorimeter*
    + *Anticoincidence Detector*
    + *Data Acquisition System*

    With its very large field of view, the LAT sees about 20% of the sky at any
    given moment. In sky-survey mode, which is the primary observing mode, the
    LAT will cover the entire sky every three hours. The observatory can also be
    pointed at targets of opportunity, and can slew autonomously when either
    instrument detects sufficiently bright gamma-ray bursts (GRBs). The LAT is
    at least 30 times more sensitive than any previous gamma-ray instrument
    flown in space, and will detect thousands of new sources during GLAST’s
    five-year primary mission.

    The LAT was assembled at the Stanford Linear Accelerator Center (SLAC), but
    with substantial hardware contributions from partners in France, Italy,
    Japan, Sweden, and the U.S. SLAC also manages the collaboration. The
    Principal Investigator is Peter Michelson of Stanford University/SLAC.

**** How the LAT Detects Gamma Rays and Rejects Cosmic Rays

    1. A gamma ray enters the LAT. It first passes through the Anticoincidence
       Detector without producing a signal.
    2. The gamma ray interacts in one of 16 thin tungsten sheets. This
       interaction converts the gamma ray into an electron and a positron via
       pair production (governed by Einstein’s equation $E=mc^{2}$).
    3. The Tracker uses silicon strips to measure the paths of the electron and
       positron, allowing the LAT to determine the arrival direction of the
       gamma ray.
    4. The electron and positron enter the Calorimeter, which measures the
       energies of the particles, and therefore the energy of the original gamma
       ray.
    5. Unwanted cosmic-ray particles produce a signal in the Anticoincidence
       Detector, which tells the Data Acquisition System to reject the
       signal. The Anticoincidence Detector rejects 99.97% of unwanted signals
       produced by cosmic rays that enter the LAT.
    6. Software in the LAT Data Acquisition System also rejects, based on
       arrival direction, unwanted gamma rays that originate in Earth’s
       atmosphere.

**** Components of the LAT

***** Tracker
      The Tracker consists of a four-by-four array of tower modules. Each tower
      module consists of layers of silicon-strip particle tracking detectors
      interleaved with thin tungsten converter foils. The silicon-strip
      detectors precisely measure the paths of the electron and positron
      produced from the initial gamma ray. The pair-conversion signature is also
      used to help reject the much larger background of cosmic rays.

***** Calorimeter
      The Calorimeter measures the energy of a particle when it is totally
      absorbed. The LAT Calorimeter is made of a material called cesium iodide
      that produces flashes of light whose intensity is proportional to the
      energies of the incoming particle. The Calorimeter also helps to reject
      cosmic rays, since their pattern of energy deposition is different from
      that of gamma rays.

***** Anticoincidence Detector (ACD)
      The Anticoincidence Detector is the first line of defense against cosmic
      rays. It consists of specially formulated plastic tiles that produce
      flashes of light when hit by charged-particle cosmic rays (but not by
      gamma rays, which are electronically neutral). The ACD forms a "hat" that
      fits over the tracker.

***** Data Acquisition System (DAQ)
      The Data Acquisition System is the brain behind the LAT. It collects
      information from the Tracker, the Calorimeter, and the Anticoincidence
      Detector and makes the initial distinction between unwanted signals from
      cosmic rays and real gamma-ray signals to decide which of the signals
      should be relayed to the ground. This system also does an on-board search
      for gamma-ray bursts. The DAQ consists of specialized electronics and
      microprocessors.

*** GLAST Burst Monitor (GBM)

    The GBM consists of 12 detectors made of sodium iodide for catching X rays
    and low-energy gamma rays, and two detectors made of bismuth germanate for
    high-energy gamma rays. Together, they detect cover X rays and gamma rays in
    the energy range between 8 keV to 30 MeV, overlapping with the LAT’s
    lower-energy limit. The GBM detectors will view the entire sky not occulted
    by Earth, and are expected to pick up about 200 GRBs per year, as well as
    solar flares and other transient events. The combination of the GBM and the
    LAT provides a powerful tool for studying GRBs over a very wide range of
    energies.

    The development of the GBM and analysis of its observational data is a
    collaborative effort between the National Space Science and Technology
    Center in the U.S. and the Max Planck Institute for Extraterrestrial Physics
    (MPE) in Germany. The instrument is managed at NASA's Marshall Space Flight
    Center in Huntsville, Alabama. Charles "Chip" Meegan of NASA Marshall is the
    Principal Investigator. In July 2007 Jochen Greiner of Max Planck replaced
    the now-retired Giselher Lichti as Co-P.I.

**** How the GBM Detects Gamma-Ray Bursts

     1. An X ray or low-energy gamma ray from deep space enters one of the 12
        GBM low-energy detectors, which are flat disks made of a sodium-iodide
        material that produces a faint flash of light when struck. A
        photomultiplier tube detects the flash.
     2. The 12 detectors are located on opposite sides of the GLAST satellite,
        so they face different directions in the sky.
     3. When gamma rays from a gamma-ray burst reach the GBM, the disk facing
        the burst will detect more gamma rays than the others.
     4. By comparing the rate of signals from four or more detectors, the GBM
        can triangulate the arrival direction of the burst to within several
        degrees.
     5. Two high-energy detectors made of bismuth germanate pick up
        higher-energy gamma rays and measure their energies in much the same way
        as the low-energy detectors.

**** Components of the GBM

***** Low-Energy Detectors
      The low-energy sodium iodide detectors detect X rays with about 8 keV of
      energy up to gamma rays with about 1 MeV. They provide the locations of
      gamma-ray bursts to within several degrees, and they overlap in energy
      with other missions that detect GRBs, such as NASA’s Swift satellite. The
      low-energy detectors are mounted in four banks consisting of three
      detectors each. The 12 detectors are oriented in various directions so
      they face different parts of the sky. The GBM uses the signals from the
      low-energy detectors to detect burst locations.

***** High-Energy Detectors
      The high-energy detectors are made of bismuth germanate, which is
      sometimes abbreviated BGO because germanate is a germanium oxide. They
      cover the energy range from about 150 keV to about 30 MeV, providing a
      good overlap with the low-energy detectors at the bottom end of the
      gamma-ray energy range, and with the LAT at the high end. Bismuth
      germanate is a high-density material that provides better sensitivity at
      high energies. The two high-energy detectors are positioned on opposite
      sides of the spacecraft, providing nearly full sky coverage.

***** Data Processing Unit
      The electronics and microprocessors in the data processing unit receive
      and analyze the data from the low-energy detectors and high-energy
      detectors. It detects GRBs, determines their energies and arrival
      directions, and sends data to the GLAST spacecraft for transmission to the
      ground.

* The Fermi LAT instrument ([[http://www-glast.stanford.edu/instrument.html][fonte]])

This is a brief description of the instrument. For more details see [[http://arxiv.org/abs/0902.1089][the full
technical description of the LAT]] and [[http://www-glast.slac.stanford.edu/software/IS/glast_lat_performance.htm][a summary of its performance]].

** Principles of operation

   Unlike visible light, high-energy gamma rays cannot be refracted by a lens or
   focused by a mirror. Instead, they are detected with the same technology as
   the detectors used in high-energy particle accelerators.

   Incoming gamma rays pass freely through the thin plastic anticoincidence
   detector, while charged cosmic rays cause a flash of light, allowing the LAT
   identify the relatively rare gamma rays. A gamma ray continues until it
   interacts with an atom in one of the thin tungsten foils, producing two
   charged particles: an electron and a positron. They proceed on, creating ions
   in thin silicon strip detectors. The silicon strips alternate in the X and Y
   directions, allowing the progress of the particles to be tracked. Finally the
   particles are stopped by a cesium iodide calorimeter which measures the total
   energy deposited. The information from the anticoincidence detector, tracker
   and calorimeter is combined to estimate the energy and direction of the gamma
   ray.

** Construction

   This cutaway view shows more details of the instrument's design. The 18
   tungsten converter layers and 16 dual silicon tracker planes are stacked in
   16 modular "towers" (37 cm square and 66 cm tall). Each of the 16 calorimeter
   modules consists of 96 long, narrow CsI scintillators, stacked in 8 layers,
   alternating in orientation so that the location and spread of the deposited
   energy can be determined. The plastic anticoincidence scintillator around the
   outside is made of 89 individual sections so that it can distinguish charged
   particles coming from the direction of the incident gamma ray and ignore
   others. A sophisticated, flexible data acquisition system combines
   information from all the components to decide when a likely gamma-ray has
   been detected and to choose what information to send to the ground. The upper
   part of the instrument is wrapped in a multilayer "blanket" which provides
   thermal insulation and protects from micrometeoroids and debris.

   The LAT is 0.72 m deep and 1.8 m square. Its total mass is 2789 kg. It uses
   650 W of electric power.

** Calibration and Performance

   Parts of the instrument were calibrated in particle beams at CERN, SLAC and
   GSI, but it was not possible to test the whole instrument with realistic
   gamma-ray and proton beams. The calibration relies on a detailed Monte Carlo
   simulation of all the instrument's components. The simulation software was
   refined until its predictions agreed with the results obtained from beam
   tests and cosmic ray muons.

   The performance of a gamma-ray telescope can be characterized by its
   effective area, field of view and angular resolution. The field of view is
   very wide, with useful response out to about 60° from the instrument axis,
   covering about 20% of the sky. The angular resolution depends on the
   gamma-ray's energy, its incidence angle, and where it interacts in the
   detector. The point spread function for on-axis gammas has a 68% containment
   radius of about 3° at 100 MeV and 0.04° at 100 GeV. The effective area in the
   center of the field of view is about 7000 cm2 at 1 GeV, decreasing at lower
   and higher energy.  Operation

   The Fermi spacecraft orbits the earth in about 96 minutes. It is oriented to
   point the LAT upward at all time, so the earth does not block the view. On
   alternate orbits Fermi rocks to the left and right, allowing the LAT to cover
   more of the sky. Thus the whole sky can be surveyed in two orbits. This mode
   of operation allows for constant monitoring of any gamma-ray emitter over
   days, weeks, months and years.

   When a strong gamma-ray burst occurs, Fermi will point itself at the location
   of the burst for a few hours to collect extra data.

** Subsystems

   The LAT was produced as four separate subsystems which were built and tested
   separately:

   + Tracker/converter (TKR): [[http://dx.doi.org/10.1016/j.astropartphys.2007.08.010][Technical description]]
   + Calorimeter (CAL): [[http://dx.doi.org/10.1109/NSSMIC.1997.672494][Technical description]]
   + Anticoincidence (ACD): [[http://dx.doi.org/10.1016/j.astropartphys.2006.12.003][Technical description]]
   + Data Acquisition (DAQ): The best description is in the [[http://arxiv.org/abs/0902.1089][LAT instrument
     paper]].

* AMS-02: lo strumento ([[http://www.ams02.org/it/che-cosa-ams/strumenti/][fonte]])

  AMS-02 è uno spettrometro magnetico di grandi dimensioni realizzato per
  operare nello spazio. Tra le tante sfide del progetto, la principale è stata
  quella di mettere a punto un sistema magnetico in grado di lavorare nello
  spazio in sicurezza e per un periodo prolungato.

  La Collaborazione di AMS ha sviluppato due magneti:

  - Un magnete permanente (Permanent Magnet, PM) che opera a temperatura
    ambiente. Il PM è composto da 6000 blocchi in lega di Neodimio accuratamente
    magnetizzati e poi incollati assieme. Questo magnete è stato già utilizzato
    nel prototipo di AMS, AMS-01, che ha volato nella missione Shuttle STS-91
    nel 1998.
  - Un magnete superconduttore (Superconducting Magnet, SCM) in grado di operare
    a una temperatura di 4 gradi sopra lo zero assoluto (0 K). Il SCM è composto
    da 14 bobine di materiale superconduttore avvolte su una robusta struttura
    d’alluminio. La corrente che circola permanentemente nelle bobine genera al
    centro di AMS un campo magnetico fino a 0.87 Tesla di intensità. Per essere
    mantenuto alla bassissima temperatura di lavoro, il SCM necessita di un
    continuo raffreddamento realizzato tramite un contatto termico con una
    grande massa di elio superfluido (2500 litri) alla temperatura di 1.8
    Kelvin. Il magnete superconduttore è stato testato nel large space simulator
    al centro ESA, ESTEC di Nordwijk in Olanda nell’aprile del 2010 dando buoni
    risultati.

  Entrambi i sistemi magnetici hanno la stessa configurazione del campo, il
  cosiddetto anello magico, che assicura al magnete un momento di dipolo netto
  trascurabile e impedisce che, una volta installati nello spazio, ci siano
  accoppiamenti con il campo magnetico terrestre, cosa che disturberebbe
  l’orbita della Stazione Spaziale. I due magneti hanno anche dimensioni simili
  e presentano le stesse interfacce con i rivelatori dell’esperimento, sono
  quindi meccanicamente intercambiabili.

  L’elettronica di AMS è una sfida tecnologica a sè stante. Lo spazio è infatti
  un ambiente estremamente ostile per le apparecchiature elettroniche data la
  presenza della radiazione cosmica. L’elettronica di AMS consta di oltre 600
  diversi computer dotati di chip tolleranti alla radiazione, sviluppati
  appositamente per la fisica delle alte energie, circa 10 volte più veloci dei
  normali computer.

  Per una descrizione dei sottosistemi di AMS-02, segui i link sotto riportati:

  - *[[http://www.ams02.org/it/che-cosa-ams/strumenti/il-magnete/][Il Magnete]]* curva in direzioni opposte particelle e antiparticelle
  - *[[http://www.ams02.org/it/che-cosa-ams/strumenti/il-trd/][Il Transition Radiation Detector (TRD)]]* identifica la popolazione di
    elettroni e positroni presente nei raggi cosmici
  - *[[http://www.ams02.org/it/che-cosa-ams/strumenti/il-tof/][Il Time-of-Flight System (ToF)]]* avvisa i rivelatori dell’arrivo di un raggio
    cosmico
  - *[[http://www.ams02.org/it/che-cosa-ams/strumenti/il-tracker-al-silicio/][Il Silicon Tracker (Tracker)]]* rileva il segno della carica della particella
    permettendo di separare la materia dall’antimateria
  - *[[http://www.ams02.org/it/che-cosa-ams/strumenti/il-rich/][Il Ring-Imaging Cherenkov Detector (RICH)]]* misura con alta precisione la
    velocità dei raggi cosmici
  - *[[http://www.ams02.org/it/che-cosa-ams/strumenti/lecal/][L’Electromagnetic Calorimeter (ECAL)]]* misura l’energia di elettroni,
    positroni e raggi $\gamma$
  - *[[http://www.ams02.org/it/che-cosa-ams/strumenti/lacc/][L’Anti-Coincidence Counter (ACC)]]* rigetta i raggi cosmici che attraversano
    le pareti del magnete
  - *[[http://www.ams02.org/it/che-cosa-ams/strumenti/il-tas/][Il Tracker Alignement System (TAS)]]* controlla la stabilità
    dell’allineamento del tracciatore al silicio
  - *[[http://www.ams02.org/it/che-cosa-ams/strumenti/lo-star-tracker-e-il-gps/][Lo Star Tracker e il GPS]]* stabiliscono l’ora, la posizione e l’orientamento
    dell’esperimento AMS-02
  - *[[http://www.ams02.org/it/che-cosa-ams/strumenti/lelettronica/][L’elettronica]]* trasforma i segnali provenienti dai rivelatori di particelle
    in informazioni digitali pronte per essere trasmesse a terra e
    successivamente analizzate
